# Copyright 2019 MaidSafe.net limited.
#
# This SAFE Network Software is licensed to you under The General Public License (GPL), version 3.
# Unless required by applicable law or agreed to in writing, the SAFE Network Software distributed
# under the GPL Licence is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. Please review the Licences for the specific language governing
# permissions and limitations relating to use of the SAFE Network Software.

[package]
name = "jsonrpc-quic"
version = "0.0.1"
description = "JSON-RPC over QUIC for safe-authd comm"
authors = ["bochaco <gabrielviganotti@gmail.com>"]
publish = false
license = "GPL-3.0"
repository = "https://github.com/maidsafe/safe-api"
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
directories = "1.0.2"
futures = "~0.1.21"
log = "0.4.6"
quinn = "~0.3.0"
rand = "0.6.5"
serde = "1.0.91"
serde_json = "1.0.41"
tokio = "0.1.6"
tokio-current-thread = "0.1"
tokio-reactor = "0.1.1"
url = "1.7.2"
