[package]
name = "sn_url"
version = "0.0.1"
description = "Safe URL"
authors = ["bochaco <gabrielviganotti@gmail.com>", "Josh Wilson <joshuef@gmail.com>"]
license = "MIT OR BSD-3-Clause"
repository = "https://github.com/maidsafe/sn_api"
include = ["Cargo.toml", "src/*"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
log = "~0.4"
multibase = "~0.9"
serde = "1.0.123"
sn_data_types = "~0.18"
thiserror = "1.0.23"
uhttp_uri = "~0.5"
url = "2.2.0"
urlencoding = "1.1.1"
xor_name = "1"

[dev-dependencies]
anyhow = "1.0.38"
rand = "~0.7"
